services:
 
  db:
    image: postgres
    container_name: postgresql
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
 

