services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  graphql-engine:
    image: hasura/graphql-engine:v2.27.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: v
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:test123@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: warn
      HASURA_GRAPHQL_REDIS_URL: "redis://redis:6379"
      HASURA_GRAPHQL_RATE_LIMIT_REDIS_URL: "redis://redis:6379"
volumes:
  db_data: